version: '3.3'
services:
  redis:
    image: redislabs/rejson:latest
    volumns:
      - ./redis:/data
  dev:
    restart: on-failure
    build .
    enviroment:
      - redis=redis://redis:6379
    volumns:
      - ./workspace:/root/workspace
    ports:
      - '8080:3000'
