version: '3.3'
services:
  redis:
    image: redislabs/rejson:latest
    volumes:
      - ./redis:/data
  dev:
    restart: on-failure
    build: .
    environment:
      - redis=redis://redis:6379
    volumes:
      - ./workspace:/root/workspace
    ports:
      - '8080:3000'
